apiVersion: 1

datasources:
  - name: InfluxDB-PulseUK
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: resilience_metrics
    user: admin
    jsonData:
      version: Flux
      organization: pulse-uk
      defaultBucket: resilience_metrics
      tlsSkipVerify: true
    secureJsonData:
      token: pulse_uk_2026
    isDefault: true
    editable: true
